### ISSUE TITLE
No such file or directory: 'sumo' issues with Traffic manager

### ISSUE THREAD

**Issue by zhoujiawei3** [PJLab-ADG/DriveArena#39]
(drivearena_tf) D:\Carla_build\carla\PythonAPI\DriveArena>python ./TrafficManager/sim_manager_only.py
No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7'
(drivearena_tf) D:\Carla_build\carla\PythonAPI\DriveArena>python ./TrafficManager/sim_manager_only.py
No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7'
No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7'
Model initialized at 02:53:15.742.
No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7'
No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7'
No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7'
Network building finished at 02:53:24.175.
Traceback (most recent call last):
  File "./TrafficManager/sim_manager_only.py", line 251, in <module>
    main()
  File "./TrafficManager/sim_manager_only.py", line 247, in main
    sim_manager.run_simulation()
  File "./TrafficManager/sim_manager_only.py", line 223, in run_simulation
    self.initialize_simulation()
  File "./TrafficManager/sim_manager_only.py", line 133, in initialize_simulation
    self.model.start()
  File "D:\Carla_build\carla\PythonAPI\DriveArena\TrafficManager\LimSim\simModel\Model.py", line 132, in start
    traci.start([
  File "D:\Anaconda_envs\envs\drivearena_tf\lib\site-packages\traci\main.py", line 145, in start
    sumoProcess = subprocess.Popen(cmd2, stdout=stdout)
  File "D:\Anaconda_envs\envs\drivearena_tf\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\Anaconda_envs\envs\drivearena_tf\lib\subprocess.py", line 1327, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
Network information commited at 02:53:24.193.

**Comment by zhoujiawei3** [comment]
When I run `python ./TrafficManager/sim_manager_only.py` This error occurs

**Comment by zhoujiawei3** [comment]
![image](https://github.com/user-attachments/assets/d70c7fab-c8ed-4196-bb68-c793ce84dfa8)

**Comment by zhoujiawei3** [comment]
The similar error happens in Linux too
![image](https://github.com/user-attachments/assets/c6ae3118-2935-4b1b-bad6-b8452f4cae84)

**Comment by zhoujiawei3** [comment]
Maybe the download of sumo can be mentioned in the install instruction

**Comment by jzliu02** [comment]
请问您在Windows上解决这个问题了吗？我安装了SUMO后仍然报相同的错误。SUMO_HOME也已经设置了。

**Comment by jzliu02** [comment]
> 请问您在Windows上解决这个问题了吗？我安装了SUMO后仍然报相同的错误。SUMO_HOME也已经设置了。

我通过在代码中显式指定sumo路径运行成功了。
